### ISSUE TITLE
SPGo: Publish local workspace command not work

### ISSUE THREAD

**Issue by paulinhps** [readysitego/spgo#12]
Hello @ sg-chrishasz!

Great API!

But, I'm trying to use the SPGo command: Publish local workspace to no avail. Or maybe you're not fully understanding your concept.

In my view this command would publish all files with check out inside my workspace, correct?

**Comment by sg-chrishasz** [comment]
Hello @paulinhps -

Thank you for using SPGo! You are correct, the `>SPGo : Publish Local Workspace` command will publish all files that you have checked out from the server, but that is not all. This command has two features:
* to push all local files under the local `src` folder to their relative path on the server, if they do not yet exist on the server. 
* to publish all checked out files in your local workspace (this is your usecase)

Can you provide more details on the error you are seeing? It may help to also copy any text from the output tab in Visual Studio Code (scoped to SPGo in the dropdown).

If you can provide that data, I can help resolve this issue.

Thanks!
- Chris

**Comment by paulinhps** [comment]
Hello @ sg-chrishasz 
Thanks for the reply! This is the problem, you do not have a message. The `"Publishing workspace"` loading message runs and runs for a while and then stops, but the files are not pushed or published.

File a file is published correctly using `Publish Major Version of current file`

SPGo has log files?

**Comment by paulinhps** [comment]
@sg-chrishasz, today this function performed correctly...

Maybe because I rebooted my pc.

Thanks you
