### ISSUE TITLE
Receiving an error when saving a file

### ISSUE THREAD

**Issue by negativepitch** [readysitego/spgo#19]
I am able to check-in/out files, and publish major/minor versions of files through SPGo, however when I try to just save these files (CTRL + S), I receive the error below. 

![image](https://user-images.githubusercontent.com/30101407/34526301-1af3cc3a-f070-11e7-81e9-1a97545fa58c.png)

**Comment by sg-chrishasz** [comment]
Hi @negativepitch -

I've replicated this issue locally and can confirm the bug. I will release a fix with the 1.0.1 release this week. In the meantime, as a workaround, you can use check-out/publish to upload files to the server.

Thanks for using SPGo!
-Chris

**Comment by sg-chrishasz** [comment]
Resolved in build 1.0.1
