### ISSUE TITLE
populate local workspace:  Cannot set property 'domain' of undefined

### ISSUE THREAD

**Issue by PowPowB** [readysitego/spgo#21]
Hi - I'm wondering if you can help me with this error during "populate local workspace":  Cannot set property 'domain' of undefined

1.  sharePointSiteURL:  http://abc.srv.company.com/c/site
2.  authenticationType:  NTLM

*Intranet
*vpn'd into company

Format:  
uid: domain\username
pwd:  pwd

*when I try email and pwd, I don't get an error message but I get "Starting File Synchronization" but nothing happens.

Thank you.
PowPow

**Comment by sg-chrishasz** [comment]
Hello @PowPowB -

I can confirm that this is a bug in build 1.0.1. I will release a fix for it in release 1.1, due this week.

Thanks for using SPGo!
-Chris

**Comment by PowPowB** [comment]
Oh okay, I thought the issue was going to be on my end... Also, I appreciate the quick response.  Thank you!

**Comment by sg-chrishasz** [comment]
@PowPowB - I have released VSCode 1.1.0, can you verify that this issue has been resolved?

Thanks,
-Chris

**Comment by PowPowB** [comment]
It works!  Thanks!
    On Wednesday, January 17, 2018, 12:00:55 AM EST, Chris Hasz <notifications@github.com> wrote:  
 
 
@PowPowB - I have released VSCode 1.1.0, can you verify that this issue has been resolved?

Thanks,
-Chris

**Comment by sg-chrishasz** [comment]
Thanks @PowPowB . Closing this issue.
