### ISSUE TITLE
[Feature Request] Invalid user credentials

### ISSUE THREAD

**Issue by SeanCMrsh** [readysitego/spgo#23]
Hi,
I have installed spgo (0.10.1) - which looks to be exactly what I need for SP module builds.
However, when I save a file and am challenged for username and password - I get "Invalid user credentials". I am simply entering domain\username.
I have on premise SP2013 and using standard company network (NTML w. kerberos).
Any idea what is going wrong?
Thanks

**Comment by koltyakov** [comment]
Hey Sean,

Authentication won't work with NTLMv2 and Kerberos it's something which can't be fixed.
For such cases the only possible option to extend SharePoint web application to other supported authentication strategies, NTLM (v1), for example, FBA, ADFS or App Model.

**Comment by SeanCMrsh** [comment]
Thanks Andrew. Understood.

How about this though?– could you allow WEBDAV option where we add site URL as the path…i.e.  \\server\sites\site\siteassets
I have had success using gulp-changed which is happy to deploy via webdav with no authentication required (because laptop is logged in).
This works – but the setup is a pain (you need all the node modules etc.) – SPGo is far more elegant.

const gulp = require('gulp');
const changed = require('gulp-changed');

const SRC = 'src/*';
const DEST = '\\\\server\\sites\\site\\siteassets;

gulp.task('deploy',  () =>
    gulp.src(SRC)
        .pipe(changed(DEST))
        .pipe(gulp.dest(DEST))
);

**Comment by koltyakov** [comment]
Oh, bwt, the solution might be to change registry key on the server
`HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LmCompatibilityLevel` to 5

**Comment by SeanCMrsh** [comment]
Nope - already 5 :-)

**Comment by koltyakov** [comment]
> This works – but the setup is a pain (you need all the node modules etc.) – SPGo is far more elegant.

When a WebDAV folder is mapped, windows involved to authentication. When gulp plugin uses the folder in an anonymous way.

In case of SPGo, `node-sp-auth` (Node.js module) takes care of authentication. NTLM part of auth uses [node-http-ntlm](https://github.com/SamDecrock/node-http-ntlm/issues/59) library. And here is the general issue with clients which don't support NTML2 without fallback to NTLM1.

**Comment by SeanCMrsh** [comment]
OK. I can't change the SP auth model in this case, so looks like I will probably need to go forward using gulp-changed to do deploys. I will keep an eye out in case you can figure out a webdav method that works.
Thanks for your help.

**Comment by sg-chrishasz** [comment]
@SeanCMrsh - I'm going to track this as an enhancement, but NTLM v2 support is not available right now via node-sp-auth as @koltyakov mentions above.

{This library)[https://github.com/gautamsi/node-ntlm-client] appears to support NTLMv2, but I'm unable to verify this as I do not have access to an NTLMv2 environment. If you want to work with the author of node-sp-auth at https://github.com/gautamsi/node-ntlm-client, that would allow SPGo to support your use case without needing to fall back to WebDav.

Thanks,
Chris

**Comment by sg-chrishasz** [comment]
Hello @SeanCMrsh 

@s-KaiNet is finalizing NTLMv2 support for [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) and is looking for testers. Can you test the steps in [this post](https://github.com/s-KaiNet/node-sp-auth/issues/51#issuecomment-400489446) and let us know the results?

Thanks!

**Comment by akupaka** [comment]
In my environment I used SP2013 on-premises with Kerberos authentication enabled (with fallback to NTLM by default) and SPGo v1.30.1 worked just fine (also 1.30.0 and build before that worked as well).
I used domain\username form to authenticate.

**Comment by sg-chrishasz** [comment]
@SeanCMrsh, @akupaka  Thanks for testing this out. Great to see the community coming together in support of these projects!

**Comment by sg-chrishasz** [comment]
I published SPGo 1.3.2 to the VS Marketplace which adds NTLM v2 support to SPGo!
