### ISSUE TITLE
Automatic uploading of minified files (or other files copied)

### ISSUE THREAD

**Issue by bernhardk4t** [readysitego/spgo#24]
I use minify-extension in VS Code. The minified file is not uploaded to the SharePoint location automatically. Also when copying/pasting a file in a synched folder it is not uploaded automatically.
Maybe this should be at least an option in SPGo?

**Comment by sg-chrishasz** [comment]
Hello @bernhardk4t !

I can think of a couple ways to solve this issue, but wanted you feedback on which solution would work best.

**Option 1: Extend Glob support for the `SPGo> Publish local workspace` command.** 
I could add an optional configuration setting to the spgo.json file which holds a glob pattern. When you issue the `SPGo > Publish local workspace` command, I would only publish files matching the glob pattern (e.g. '/**/*.min.js'). This is a pretty straight-forward path to supporting files minified by a 3rd party tool. The down-side is that it would not give you the ability to minifiy and upload on save.

**Option 2: Build Minify/Uglify functionality into SPGo**
I could look to adding 3rd party libraries to SPGo which could be used to minify or uglify common filetypes.  This is a more complex option, but would provide a cleaner user experience at the expense of package lock-in.

In the mean-time, if you have enabled publishing on your current SP farm, you could use the following workaround for your minified files:
 1. Set your publishingScope to 'None' in your SPGo.json file
 2. use the `SPGo > Check Out` command to check out the minified file from the server. (if the file has not been saved to the server yet, use the `SPGo > Publish a major version` command to push the file to the server.)
 3. When you are done with your edits, use the  `SPGo > Publish a major version` or `SPGo > Publish a minor version` commands to persist your changes to the server.
<repeat as necessary until you are complete>

Let me know your thoughts.
Thanks,
-Chris

**Comment by bernhardk4t** [comment]
Hello @sg-chrishasz ,

thanks for your thoughts and feedback! I think option 1 is ok as it does not mix up functionality of the extensions. One general question as I have not found it in the readme.md - does "Publish local workspace" only publish modified files?
Would there also be a way that the SPGo checks for new or changed files in the remoteFolders (not only the currently opened and saved file)?

Cheers, Bernhard

**Comment by sg-chrishasz** [comment]
Hello @bernhardk4t !

I have just published version 1.2.0 of SPGo to the VS Code marketplace. This new version supports Glob patterns for the `>SPGo: Publish local workspace` command. I have included an example configuration file below, which assumes that all minified files take the format `<file>.min.<ext>`.

```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://tenant.sharepoint.com/sites/project1",
    "publishingScope": "none",
    "authenticationType": "Digest",
    "publishWorkspaceGlobPattern": "/**/*.min.*",
    "remoteFolders": [
        "/siteAssets/"
    ]
}
```

Thanks for using SPGo!
-Chris

**Comment by bernhardk4t** [comment]
Thanks, great new feature!

**Comment by bernhardk4t** [comment]
Sorry for being late for really testing this - I can't get this to work using your example above (with my own tenant of course). What I do is:
> In SiteAssets I created a test.css
> this file was automatically uploaded by SPGo when saving
> now I'm running F1 + minify and a test.min.css is created locally in the SiteAssets library
> this file is not automatically uploaded
Am I missing something?

**Comment by sg-chrishasz** [comment]
Hello @bernhardk4t !

Uploading files that are minified by an external tool still requires a manual step on your part. Here are the two options that you have:

**Manually upload a single file**
- after step `unning F1 + minify and a test.min.css is created locally in the SiteAssets library`
- left-click on the minified file in the VSCode file viewer
- Select `SPGo: Publish a major version of the current file` (can also select `minor` version)
- **your file will be published to the server**

**Manually upload all minified files**
- after step `unning F1 + minify and a test.min.css is created locally in the SiteAssets library`
- configure the `"publishWorkspaceGlobPattern": "/**/*.min.*"` node in SPGo.json as above
- Open the VSCode command window `ctrl+shift+P` and use the command `SPGo: Publish local workspace` to publish all files, which match the above Glob pattern, to the server.
- **your file(s) will be published to the server**

Thanks,
Chris

**Comment by bernhardk4t** [comment]
Got it this time... ;-) Works perfectly.
Thanks a lot for making this possible!

Cheers, Bernhard
