### ISSUE TITLE
Unable to Authenticate when Office 365 MFA is Enabled

### ISSUE THREAD

**Issue by ChrisRomp** [readysitego/spgo#32]
Hello,

"Digest" authentication does not work when using Multi-Factor Authentication (at least I think this is the cause). The extension says "Invalid user credentials" when logging in. This also doesn't work with the "app password" so I'm not 100% certain MFA is the true case, but it seems likely.

When I write scripts using [SharePoint PnP PowerShell](https://github.com/SharePoint/PnP-PowerShell), specifying the -UseWebLogin switch will pop an Office 365 authentication form which can be used to retrieve an OAuth token that is used to process the request. Do you think something like this might be possible with SPGo?

Thanks,
Chris

**Comment by ChrisRomp** [comment]
@koltyakov OnDemand looks pretty close to the UseWebLogin approach that PnP PowerShell uses (pops a form and gets a token). I like this approach since it usually just pops the form and closes right away so I don't even have to re-enter my credentials if I'm already logged into SharePoint Online.

**Comment by koltyakov** [comment]
Could you try/check the first option with app password? All the actions should be tracked on user account demand. 

OnDemand, yep, very similar, yet node-sp-auth uses electron for opening pop up window and getting fedauth token. If I’m not wrong having browser logged in won’t by pass the session. So you got to enter the creds after token ttl is over. Let’s wait for @sg-chrishasz to know if this auth strategy can be used within SPGo.

**Comment by ChrisRomp** [comment]
I don't receive the "invalid user credentials" error when using my app password, so yes it appears to be MFA-related.

**Comment by sg-chrishasz** [comment]
Everyone-

I’m out of the office through Sunday. I’ve had a couple feature requests for MFA, and if it is possible to extend SPGo to leverage the OnDemand with capabilities of node-sp-auth, then I’ll definitely prioritize this for the 1.3.0 release.

I’ll keep everyone posted.

Chris

On Apr 10, 2018, at 10:24 AM, Chris R <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't receive the "invalid user credentials" error when using my app password, so yes it appears to be MFA-related.

**Comment by sg-chrishasz** [comment]
I've had a chance to review the MFA spec (for Office 365 / SharePoint Online) and it is something that I'll be able to implement in SPGo. It will need a custom implementation as VSCode does not expose the electron library natively.

I need to travel again this week, but I'll hope to get this feature implemented by EoW next week (April 27).

@ChrisRomp can you confirm that you/your client has MFA configured similarly to the method described in [this](https://docs.microsoft.com/en-us/office365/enterprise/multi-factor-authentication-for-your-office-365-dev-test-environment) article?

**Comment by ChrisRomp** [comment]
That's awesome! We just authenticate through the standard Azure AD MFA approach (looks like yes that's what the article references). It can get a code from the app, SMS, or we can just click "approve" in the app. It's not a third-party MFA provider generating the claim.

**Comment by sg-chrishasz** [comment]
@ChrisRomp & @koltyakov -

It looks like a native MFA solution within VSCode is not possible at this time. Ultimately, VSCode does not (to my knowledge or research) allow access to the underlying electron apis, which blocks me using the solution provided by `node-sp-auth`. Nor does VSCode allow me to open a browser session where I could load the MFA login page from Office 365. Additionally, none of the supported authentication flows in Office 365 allow remote MFA.

That said, the workaround that @koltyakov suggested above - using app passwords - is a viable option. 

I will continue to look for a 100% solution to this issue, but for now I will close it as resolved and add documentation describing how to use SPGo in an MFA-enabled instance, and the steps necessary to generate an app password.

**Comment by Germain-Italic** [comment]
Is there any update on this?

**Comment by ChrisRomp** [comment]
> Is there any update on this?

 @Germain-Italic - We've just continued with using a non-MFA-enabled service account with SPGo as part of our build pipeline.  Also a quick glance doesn't reveal any relevant updates to [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth).  [This issue](https://github.com/s-KaiNet/node-sp-auth/issues/69) seems to indicate there aren't plans to support 2FA/MFA via that library.

**Comment by Germain-Italic** [comment]
Bad news. Thank you for your update.
