### ISSUE TITLE
Feature Request: Default Update Message

### ISSUE THREAD

**Issue by ChrisRomp** [readysitego/spgo#35]
It would be nice if we could change the default "Updated by SPGo" check-in message, maybe as a parameter in SPGo.json or (better) as a user setting.

**Comment by sg-chrishasz** [comment]
Hello @ChrisRomp !

How are you currently managing file check-in/check-out? If you are using the context menu, or hotkeys (`alt+p` or `alt+shift+p`) for publishing minor or major versions, you should see a text entry box at the top of your open code window which will allow you to.

I can confirm that if you have configured your `publishingScope` property in the config file a publish a minor or major version, then SPGo will not show the input box. I'll fix that in the next version.

**Comment by ChrisRomp** [comment]
Sorry for the delayed response. I publish with `Alt+Shift+P` and the text input does appear at the top, defaulted with "Updated by SPGo." I'm requesting if we can change the default "Updated by SPGo" message how? I know we can type over the default text, but I'm talking about changing what's suggested. Thanks!

**Comment by sg-chrishasz** [comment]
Ahh, that makes sense. I'll add that as an optional config parameter in 1.2.4.

**Comment by sg-chrishasz** [comment]
I have added the `publishingScope` config property to SPGo 1.2.4 and published to the VSCode Marketplace.

**Comment by ChrisRomp** [comment]
You mean `checkInMessage`, right? 😁

**Comment by sg-chrishasz** [comment]
Yes! Late night copy/paste error!
