### ISSUE TITLE
Incorrect work in case if git used

### ISSUE THREAD

**Issue by Forket** [readysitego/spgo#36]
Seams that in case when I use git for version control, SPGO work in a wrong way.
In attachment there is error message.
![screenshot_2018-04-30 14-19-05_forket](https://user-images.githubusercontent.com/6735288/39424932-a1735ec0-4c81-11e8-9b83-720467267961.png)

**Comment by sg-chrishasz** [comment]
Hello @Forket!

Can you tell me which operation you were attempting when you received this error? That will help me diagnose on my side.

**Comment by Forket** [comment]
Hello, @sg-chrishasz .
It's hard to tell exactly. But will define 2 cases:
1. It's when I have in SPGo.json config file value of publishingScope = SaveOnly. As I understand it will trigger some actions on file save action.
2. take a look at the recorded video. it's when I perform compare with server version operation.
https://www.youtube.com/watch?v=QN1q4IIB7C4

For now it's not critical, because when I use "Publish major version of the file" it works well. But I think you have to review functionality taking into account case when VSCode workspace is under git.

Thanks

**Comment by Forket** [comment]
Here is another case, when I make a checkout of a text file (which has JSON content). It can't perform the action (and thus doesn't show file content) because of error:
`404 - {"error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /sites/SDUFerieFonden/SiteAssets/kaps/i18n/locale-da.txt.git does not exist."}}}
`
Here is video case:
https://www.youtube.com/watch?v=f6NbdHQVYT8

**Comment by sg-chrishasz** [comment]
Hello @Forket 

Thank you for the detailed report and reproduction steps!

It looks like the issue is related to the file status check that SPGo performs when a new file is opened. In this case, it is true that the `.git` files are not present on the server, so the message that SharePoint returns is logged to the console verbatim. 

Can you confirm that there are no additional execution errors when you see this message? I don't want to suppress these type of errors as there are valid use-cases where a file is missing from the server and I want to alert the user.

**Comment by Forket** [comment]
Hello, in fact, there is an error. Also present in my previous video. I think (it's just my thoughts) that it's somehow related to this git extension. Take a look at my next video(below). In fact, the file has TXT extension, and here is the main question:
1. Why content of this file shown as [object], in fact, there is JSON content in this file (take a look at screenshot taken from SP web interface.)
2. Am I right that it's because of this error in debug console related to git file extension?

Video Case: https://www.youtube.com/watch?v=lTAQYodHj_Y 

![screenshot_2018-05-08 11-20-32_forket](https://user-images.githubusercontent.com/6735288/39749082-15215e2c-52b2-11e8-80d6-2bd86736c908.png)

**Comment by sg-chrishasz** [comment]
Thanks for the detailed error messages, I've resolved the issue in SPGo 1.2.4, which is available now on the VSCode Marketplace. A couple notes on the error:
- fortunately there was no data loss. If you look in the video(s), the report was that `<file.ext>.git` does not exist, which was technically true, as that file only existed on your local file system, and was not intended to be deployed to SharePoint.
- I am now ignoring files with .git extensions as part of the file status workflow when a new file is opened. This should keep the error logs free of detritus.

If you have any other questions, or feature requests, please let me know!
