### ISSUE TITLE
Retrieve Folders and all subfolders

### ISSUE THREAD

**Issue by quachhongak** [readysitego/spgo#38]
First, thanks for this awesome extensions. 

I was wondering if there is a way to retrieve all folders and subfolders at once. For example, when using spgo: retrieve folder, if i set the path to /sitepages it would only get the files at that level but none of the folders or nested files within that folder. I try /sitepages/* without success

Perhaps, i am missing a step. 

Cheers

**Comment by imorrish** [comment]
Similar issue. If I add to remoteFolder
"/_catalogs/masterpage/display templates/search/"

It copies all the files from this folder in the wrong source folder (drops /search/ from path). e,g. they all go into
src\_catalogs\masterpage\Display Templates

If I try adding *.html on the end of the remoteFolder item, nothing is downloaded.
Maybe space in the folder name is causing a problem?

**Comment by imorrish** [comment]
Just noticed this in the release notes:
File masking for remote file download is still in development.

**Comment by quachhongak** [comment]
Ah! Thanks for the information. I will be patient and wait then! 😊

**Comment by sg-chrishasz** [comment]
All - Thanks for your feedback and support. I've published SPGo 1.2.4 to the VSCode Marketplace, which should resolve these issues. Please reach out if you have any other issues or feature requests!

A quick note on glob strings. To download a folder, and all contained folders + files recursively, use the following format:
`/siteassets/**/*`
