### ISSUE TITLE
Error when trying to Publish File SP 2013

### ISSUE THREAD

**Issue by keldelasalas** [readysitego/spgo#40]
ERROR     ================================

Error: read ECONNRESET

Getting the error above (from Log File) when trying to Publish a JS File into SiteAssets library.
I'm able to Check-out/Discard Check-out the file but unable to PUBLISH

**Comment by sg-chrishasz** [comment]
Hello @keldelasalas! Can you confirm if the above steps resolve your issue?

**Comment by keldelasalas** [comment]
Hi! Apologies for late response, issue seems to be intermittent and happens only on our UAT Env. As mentioned above, this is likely a high-latency situation.

Thanks!

**Comment by sg-chrishasz** [comment]
No problem! I will close this issue for now, but please feel free to reopen if you can consistently reproduce the error.
