### ISSUE TITLE
Ability to delete files

### ISSUE THREAD

**Issue by quachhongak** [readysitego/spgo#44]
Thanks in advance guys!
So pull, publish works great but is it possible to delete files straight from Code?

**Comment by koltyakov** [comment]
@sg-chrishasz, as a proposal for this feature: [sppurge](https://github.com/koltyakov/sppurge) can be integrated in the same way like `sppull` and `spsave`, it used the same principals on the background.

**Comment by koltyakov** [comment]
@quachhongak, I referenced to a library which could be integrated to SPGo by the extension authors. It's a raw Node.js library and some reasonable affords needed to add it to VS Code extension. Yet, as a console command, it can be easily executed i.e. as a Gulp task.

**Comment by sg-chrishasz** [comment]
@koltyakov I will look into `sppurge` as a solution for file deletes. Thanks for the reference!

**Comment by sg-chrishasz** [comment]
I have just published 1.3.0 to the VS Marketplace which supports file delete as a context-menu command. Thanks for the feedback and support of SPGo! Closing this issue.

**Comment by quachhongak** [comment]
Thank YOU!!!
