### ISSUE TITLE
[Feature Request] Directory upload/publish

### ISSUE THREAD

**Issue by Forket** [readysitego/spgo#48]
Hi.
1. Created folder with content in mapped folder/library.
2. Tried to publish to SP - error

https://www.youtube.com/watch?v=IjOJEpWn5Bc

**Comment by sg-chrishasz** [comment]
Hello @Forket 

At this time, SPGo does not support commands issued at the folder level. Unfortunately it is not possible (or at least I am unaware) of any way to exclude folders when defining [explorer/context](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus) entries.

I will add this to the backlog for future support.

**Comment by sg-chrishasz** [comment]
Hello! I have just pushed SPGo 1.3.1 to the VSCode marketplace which will resolve this issue. Can you confirm and let me know, or close this issue?

Thanks!

**Comment by sg-chrishasz** [comment]
Hello @Forket-

I'm going to close this issue as resolved. Please feel free to reopen if you are still experiencing errors.
