### ISSUE TITLE
SharePoint 2010

### ISSUE THREAD

**Issue by stephenjjbrown** [readysitego/spgo#52]
Is SharePoint 2010 supported and/or are there plans to support it?

**Comment by koltyakov** [comment]
Hi @stephenjjbrown,

I would say, nope, SharePoint 2010 is out of scopes within the stack in general.

The auth part works for 2010, however, all the upload/publishing and download methods rely on REST API (/_api/** endpoint) which was introduced in 2013.

**Comment by stephenjjbrown** [comment]
Okay, cool. Just wondering. It might be good to include in the readme that SPGo is only > 2013.
