### ISSUE TITLE
Ability to work with Generic List forms

### ISSUE THREAD

**Issue by RAllenSinai** [readysitego/spgo#53]

**Comment by RAllenSinai** [comment]
My apologies, this is a non-issue. I only needed to format the remote folder path correctly.

**Comment by sg-chrishasz** [comment]
Hi @RAllenSinai -

I'm glad you were able to resolve the issue. Would a help article on the wiki for editing default list forms have helped?

**Comment by RAllenSinai** [comment]
Hi Chris,

Yes, a help article on the  wiki would help. I was able to load forms from a custom list, however all content between the ZoneTemplate section of the form are missing in the version of the document downloaded to my local computer.

Thank you
Raphael
