### ISSUE TITLE
Custom List Form Missing ZoneTemplate Content

### ISSUE THREAD

**Issue by RAllenSinai** [readysitego/spgo#54]
After populating the local workspace, the custom list forms ZoneTemplate section does not contain the custom HTML that exists in the form on the server.

![image](https://user-images.githubusercontent.com/37548781/42961713-353d333a-8b55-11e8-8bb6-a5fdb992a951.png)

**Comment by sg-chrishasz** [comment]
@RAllenSinai - Apologies for the delayed response here. 

This is, unfortunately, the correct behavior for SharePoint. Default form pages store the template for the file (what you see here) and the contents of the file separately. The file templates are stored on disk, but the contents are stored in the ContentDB.

SP Best practices recommend either creating custom pages (You can create branded page layouts with SPGo), and then adding the form to the page via the "Add App" feature from the ribbon, or using the Forms PowerApp for SP Modern sites.
