### ISSUE TITLE
Support for SharePoint 2010

### ISSUE THREAD

**Issue by levixking** [readysitego/spgo#58]
Is there any plans to support SharePoint 2010? I'm hoping the company I work for eventually upgrades but for now I'm stuck using SharePoint Designer unless there are plans to add this functionality in the future.

**Comment by sg-chrishasz** [comment]
Hello @levixking!

SPGo uses the unified SharePoint API, which was not available until SharePoint 2013+. The library support for all of the operations SPGo performs is not available for 2010 and so I am unable to support that version. Sorry about that.
