### ISSUE TITLE
TXT file with JSON content

### ISSUE THREAD

**Issue by Forket** [readysitego/spgo#60]
Seams that extension can't download such file :)
Here is how file looks like from web:
![image](https://user-images.githubusercontent.com/6735288/45369132-7d5a2c80-b5e5-11e8-8aef-b9f1491cfafc.png)
Here is how it looks like from VScode (just text [object Object]):
![image](https://user-images.githubusercontent.com/6735288/45369256-c611e580-b5e5-11e8-9474-b404d55fe669.png)

**Comment by sg-chrishasz** [comment]
I've confirmed this bug and will provide a fix in the next release. This issue seems to occur for any extension other than well-known file types (e.g. .css, .js, .html)

**Comment by sg-chrishasz** [comment]
Hello @Forket! Thanks for your patience here. I've tracked down the error to how sppull, a great library which SPGo uses for downloading files, uses the fs package to write data to a file. I created an issue here to track: https://github.com/koltyakov/sppull/issues/26

Once this is fixed, I'll update my package dependences and release a new SPGo build.

**Comment by koltyakov** [comment]
Thanks! Will add/fix this in SPPull to support the scenario.

**Comment by Forket** [comment]
Thqnks for your great support and product.


Thanks and regards,
Alex Sen, IT Consultant & Troubleshooter
Mobile: +48 532 292 764
Skype: aleksandr.sen
Social: LinkedIn

**Comment by koltyakov** [comment]
Just published sppull@2.3.0 which should fix the issue. Looking forward to hearing some feedback on how it works.

**Comment by sg-chrishasz** [comment]
Confirmed I can read and write json data to any file type without issue.

Thanks @koltyakov!

**Comment by sg-chrishasz** [comment]
Resolved in release 1.3.3
