### ISSUE TITLE
I am trying to edit an .aspx file, but there are regions of code unavailable...

### ISSUE THREAD

**Issue by cachavezgit** [readysitego/spgo#61]
I can edit the file in SharePoint designer but when I open it I get a message telling me there are some regions which are unavailable in safe mode, so I choose advanced mode.

In SPGo How ca I achive the same goal?

**Comment by sg-chrishasz** [comment]
Hello @cachavezgit!

If I understand correctly, you are trying to edit a SharePoint page which contains some content that lives in the content db and some content that lives on the file system, such as a page built on a publish template, or a web part page?

SPGo can edit any .aspx page which does not store content data in the contentDB, but at this time I am unable to support ghosting/unghosting pages in the content DB.
