### ISSUE TITLE
Any way to transpile the code before pushing to SP? 

### ISSUE THREAD

**Issue by simkessy** [readysitego/spgo#62]
Is there any way to transpile / babel the file before pushing to SP? 

For example. I'd like to write with ES6 but IE sucks.

**Comment by sg-chrishasz** [comment]
Hello @simkessy -

SPGo does not support a native mechanism for transpiling content, but I have had other users who have implemented transpiling/minification behaviors by disabling auto-upload (or publish) on save, and then using the  `spgo>publish workspace` command with a custom filter to only upload the transpiled, or minified files

ex - publish workspace glob notation for publishing files minified by a 3rd party tool:
`**/*.min.js`

That said, if you have any good suggestions for architecting something like this, I'd be happy to implement it (or you can clone and issue a PR).
