### ISSUE TITLE
Folders outside Libraries

### ISSUE THREAD

**Issue by tknaller** [readysitego/spgo#63]
Thank you very much for your awesome plugin! unfortunately we are usually putting our customized stuff outside any library, in a folder named _custom under the root of the sharepoint web (via all file sin sharepoint designer) - so the urls would be for example https://tenant.sharepoint.com/sites/webUnderDevelopment/_custom/myscript.js - when i add /_custom/ to the remoteFolders in SPGo.json, that folder doesn't get downloaded when using populate workspace and also isn't being downloaded when using retrieve folders - any chance that can be implemented in a future release?

**Comment by tknaller** [comment]
a few insights: event when settings camlQuery to empty in factory/downloadFileOptionsFactory.ts
`        let camlQuery : string = '';//GlobToCamlConverter.Convert(this.glob, UrlHelper.removeLeadingSlash(sharePointSiteUrl.path));`

then the issue is that sppull tries to get metadata on the items via the ListItemAllFields (which does not exist when files don't belong to libraries) in api/index.js:
´               var metadataStr = _this.options.metaFields.map(function (fieldName) {
                    return 'Files/ListItemAllFields/' + fieldName;
                }).join(',');
                if (metadataStr.length > 0) {
                    metadataStr += ',';
                }
                restUrl = restUrl.replace(/##MetadataSrt#/g, metadataStr);`
that then results in following error:
`Error in getFolderContent: 500 - {"error":{"code":"-2146232832, Microsoft.SharePoint.SPException","message":{"lang":"de-DE","value":"Das angegebene Objekt gehört zu keiner Liste."}}}`
which loosely translated means that the object does not belong to any list

**Comment by tknaller** [comment]
just found in the code of sppull: settings options.fields to an empty array could fix that, will try that tomorrow
still means there will need to be additional configuration in sppull to not-Glob but recurse anyway (just like with my dirty camlQuery hack)

**Comment by sg-chrishasz** [comment]
Nice investigation! Let's reach out to @koltyakov (sppull author) to see if he can help address this issue.
Repo here: https://github.com/koltyakov/sppull

**Comment by sg-chrishasz** [comment]
Created issue: https://github.com/koltyakov/sppull/issues/25

**Comment by koltyakov** [comment]
Thanks! Will add/fix this in SPPull to support the scenario.

**Comment by koltyakov** [comment]
Just published sppull@2.3.0 which should fix the issue. Looking forward to hearing some feedback how is works.

**Comment by sg-chrishasz** [comment]
Resolved in release 1.3.3

**Comment by tknaller** [comment]
Tank you very much @sg-chrishasz and @koltyakov, works great! really appreciate it
