### ISSUE TITLE
Workspace wrong population - files renamed and moved out of folder

### ISSUE THREAD

**Issue by tockata** [readysitego/spgo#69]
Hello and thank you for the awesome extension!

I have the following issue while using it:
We have this configuration:

> {
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://domain/subsiteName",
    "publishingScope": "None",
    "authenticationType": "Digest",
    "remoteFolders": [
        "/SiteAssets/**/*.*"
    ]
}

The real "Site Assets" structure on the server is:
    SiteAssets/js/**subsiteName**111.xxx.js
    SiteAssets/js/**subsiteName**222.yyy.js
    SiteAssets/js/**subsiteName**333.zzz.js

File names start with the same name as the **subsiteName**.

After populating the workspace the js files are shown outside the js folder and are renamed. The populated structure is the following:
    SiteAssets/js111.xxx.js
    SiteAssets/js222.yyy.js
    SiteAssets/js333.zzz.js

If the file names do not contain the subsite name everything is fine.

**Comment by sg-chrishasz** [comment]
Hello @tockata - Let me replicate this in my local environment and see what I can find. I suspect this is a case where I made an assumption about site and folder names when doing string operations.

I'll report back when I have a more definitive answer.

**Comment by sg-chrishasz** [comment]
@tockata I can confirm this is a bug. I will resolve this in the next version of SPGo!

**Comment by sg-chrishasz** [comment]
@tockata - I am working this issue right now with @koltyakov over here https://github.com/koltyakov/sppull/issues/27. Please feel free to add any additional details I may have missed.

**Comment by richyreys** [comment]
This is the same problem that i have now.

**Comment by sg-chrishasz** [comment]
All- I've just posted SPGo 1.3.5 to the VSCode Marketplace which will resolve this issue. Please reopen this issue if you are still experiencing issues.
