### ISSUE TITLE
Doesn't sync files in /search folder

### ISSUE THREAD

**Issue by imorrish** [readysitego/spgo#70]
Search site in 365 is /search (not under a managed path).
"remoteFolders": ["/_catalogs/masterpage/display templates/**/*.html"]

All sub folders under /display templates/ are populated except files from the /display templates/Search folder are copied to the parent folder "display templates"

**Comment by sg-chrishasz** [comment]
@imorrish - I've just posted SPGo 1.3.5 to the VSCode Marketplace which will resolve this issue. Please reopen this issue if you are still experiencing issues.
