### ISSUE TITLE
Couldn't find what versions of SP this works with 

### ISSUE THREAD

**Issue by kenhughlee** [readysitego/spgo#76]
I have SP2013 and my retrieve folder and populate local workspace options are not working.
I entered  {
    "sourceDirectory": "src",
    "sharePointSiteUrl": "http://XXXX.net",
    "publishingScope": "Major",
    "authenticationType": "NTLM"
} in the SPGO.json file.
Nothing happens after I enter in my user name and password

**Comment by sg-chrishasz** [comment]
Hello @kenhughlee -

VSCode introduced a bug with the 1.31 release [which broke NTLM authentication](https://github.com/Microsoft/vscode/issues/68531) for SPGo.

A workaround to get you up and running is to disable the proxy settings in VSCode settings. You can find more details here: https://github.com/readysitego/spgo/issues/73#issuecomment-462961401

**Comment by kenhughlee** [comment]
Thanks for the quick response!  I went ahead and tried setting the Proxy to 'on', and I restarted VScode and it still did not work.  I wish there was an error message or something, but nothing happens.

**Comment by kenhughlee** [comment]
Never mind.   I used retrieve folder and it worked!  Thanks  !!

**Comment by kenhughlee** [comment]
I don't know if this is a VSCode issue or if just part of my code didnt get migrated, but wherever I have XSL code, the rest of the code gets cut off.  Do you know why this is happening?
