### ISSUE TITLE
Only part of my code gets migrated

### ISSUE THREAD

**Issue by kenhughlee** [readysitego/spgo#77]
I don't know if this is a VSCode issue or if just part of my code didnt get migrated, but wherever I have XSL code, the rest of the code gets cut off. Do you know why this is happening?

**Comment by sg-chrishasz** [comment]
Hello @kenhughlee - What kind of files are you having these issues with?  (e.g. .webpart defnitions, with embedded xsl, pure xsl files). There are some types of SharePoint files, such as content pages, which store partial data in the contentDB and I want to make sure this isn't a SP-native issue. 

Can you give me an example file so that I can replicate this issue locally? 

Thanks!

**Comment by kenhughlee** [comment]
Sorry about the styling, But none of the XSL code here appears.

<asp:Content ContentPlaceHolderId="PlaceHolderPageTitle" runat="server">
	<SharePoint:ListItemProperty Property="BaseName" maxlength="40" runat="server"/>
</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderAdditionalPageHead" runat="server">
	<meta name="GENERATOR" content="Microsoft SharePoint" />
	<meta name="ProgId" content="SharePoint.WebPartPage.Document" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="CollaborationServer" content="SharePoint Team Web Site" />
	<SharePoint:ScriptBlock runat="server">
	var navBarHelpOverrideKey = &quot;WSSEndUser&quot;;
	</SharePoint:ScriptBlock>
<SharePoint:StyleBlock runat="server">
body #s4-leftpanel {
	display:none;
}
.s4-ca {
	margin-left:0px;
}
</SharePoint:StyleBlock>
</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderSearchArea" runat="server">
	<asp:ScriptManagerProxy runat="server" id="ScriptManagerProxy">
	</asp:ScriptManagerProxy>
	<SharePoint:DelegateControl runat="server"
		ControlId="SmallSearchInputBox"/>
</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderPageDescription" runat="server">
	<SharePoint:ProjectProperty Property="Description" runat="server"/>
</asp:Content>
<asp:Content ContentPlaceHolderId="PlaceHolderMain" runat="server">
	<div class="ms-hide">
	<WebPartPages:WebPartZone runat="server" title="loc:TitleBar" id="TitleBar" AllowLayoutChange="false" AllowPersonalization="false" Style="display:none;"><ZoneTemplate>
	<WebPartPages:TitleBarWebPart runat="server" HeaderTitle="testpage" Title="Web Part Page Title Bar" FrameType="None" SuppressWebPartChrome="False" Description="" IsIncluded="True" ZoneID="TitleBar" PartOrder="2" FrameState="Normal" AllowRemove="False" AllowZoneChange="True" AllowMinimize="False" AllowConnect="True" AllowEdit="True" AllowHide="True" IsVisible="True" DetailLink="" HelpLink="" HelpMode="Modeless" Dir="Default" PartImageSmall="" MissingAssembly="Cannot import this Web Part." PartImageLarge="" IsIncludedFilter="" ExportControlledProperties="True" ConnectionID="00000000-0000-0000-0000-000000000000" ID="g_9fa615b1_2fee_4597_a60c_b48cd443feee" AllowClose="False" ChromeType="None" ExportMode="All" __MarkupType="vsattributemarkup" __WebPartId="{9FA615B1-2FEE-4597-A60C-B48CD443FEEE}" WebPart="true" Height="" Width=""></WebPartPages:TitleBarWebPart>

	</ZoneTemplate></WebPartPages:WebPartZone>
  </div>
  <table class="ms-core-tableNoSpace ms-webpartPage-root" width="100%">
				<tr>
					<td id="_invisibleIfEmpty" name="_invisibleIfEmpty" colspan="3" valign="top" width="100%"> 
					<WebPartPages:WebPartZone runat="server" Title="loc:Header" ID="Header" FrameType="TitleBarOnly"><ZoneTemplate>
					
					<WebPartPages:DataFormWebPart runat="server" IsIncluded="True" AsyncRefresh="false" FrameType="None" NoDefaultStyle="TRUE" ViewFlag="8" Title="DataView 1" PageType="PAGE_NORMALVIEW" __markuptype="vsattributemarkup" partorder="2" __WebPartId="{A3EF38DD-475E-48C1-ABFC-7685B1F41E38}" id="g_a3ef38dd_475e_48c1_abfc_7685b1f41e38" listname="{42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B}" pagesize="10">
	<DataSources><SharePoint:SPDataSource runat="server" DataSourceMode="List" UseInternalName="true" UseServerDataFormat="true" selectcommand="&lt;View&gt;&lt;/View&gt;" id="spdatasource2"><SelectParameters><WebPartPages:DataFormParameter Name="ListID" ParameterKey="ListID" PropertyName="ParameterValues" DefaultValue="42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B"/><asp:Parameter Name="StartRowIndex" DefaultValue="0"/><asp:Parameter Name="nextpagedata" DefaultValue="0"/><asp:Parameter Name="MaximumRows" DefaultValue="10"/></SelectParameters><DeleteParameters><WebPartPages:DataFormParameter Name="ListID" ParameterKey="ListID" PropertyName="ParameterValues" DefaultValue="42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B"/></DeleteParameters><UpdateParameters><WebPartPages:DataFormParameter Name="ListID" ParameterKey="ListID" PropertyName="ParameterValues" DefaultValue="42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B"/></UpdateParameters><InsertParameters><WebPartPages:DataFormParameter Name="ListID" ParameterKey="ListID" PropertyName="ParameterValues" DefaultValue="42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B"/></InsertParameters>
	</SharePoint:SPDataSource></DataSources>
	
	<datafields>@Title,Task Name;@Predecessors,Predecessors;@Priority,Priority;@Status,Task Status;@PercentComplete,% Complete;@AssignedTo,Assigned To;@Body,Description;@StartDate,Start Date;@DueDate,Due Date;@Checkmark,Completed;@RelatedItems,Related Items;@respIPT,Responsible IPT;@ID,ID;@ContentType,Content Type;@Modified,Modified;@Created,Created;@Author,Created By;@Editor,Modified By;@_UIVersionString,Version;@Attachments,Attachments;@File_x0020_Type,File Type;@FileLeafRef,Name (for use in forms);@FileDirRef,Path;@FSObjType,Item Type;@_HasCopyDestinations,Has Copy Destinations;@_CopySource,Copy Source;@ContentTypeId,Content Type ID;@_ModerationStatus,Approval Status;@_UIVersion,UI Version;@Created_x0020_Date,Created;@FileRef,URL Path;@ItemChildCount,Item Child Count;@FolderChildCount,Folder Child Count;@AppAuthor,App Created By;@AppEditor,App Modified By;</datafields>
	<XSL><xsl:stylesheet xmlns:x="http://www.w3.org/2001/XMLSchema" xmlns:d="http://schemas.microsoft.com/sharepoint/dsp" version="1.0" exclude-result-prefixes="xsl msxsl ddwrt" xmlns:ddwrt="http://schemas.microsoft.com/WebParts/v2/DataView/runtime" xmlns:asp="http://schemas.microsoft.com/ASPNET/20" xmlns:__designer="http://schemas.microsoft.com/WebParts/v2/DataView/designer" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:SharePoint="Microsoft.SharePoint.WebControls" xmlns:ddwrt2="urn:frontpage:internal">
	<xsl:output method="html" indent="no"/>
	<xsl:decimal-format NaN=""/>
						<xsl:param name="dvt_apos">'</xsl:param>
						<xsl:param name="ManualRefresh"></xsl:param>
						<xsl:param name="dvt_firstrow">1</xsl:param>
						<xsl:param name="dvt_nextpagedata" />
						<xsl:variable name="dvt_1_automode">0</xsl:variable>
						<xsl:template match="/">
							<xsl:choose>
								<xsl:when test="($ManualRefresh = 'True')">
				<table width="100%" border="0" cellpadding="0" cellspacing="0">
					<tr>
						<td valign="top">
							<xsl:call-template name="dvt_1"/>
						</td>
						<td width="1%" class="ms-vb" valign="top">
							<img src="/_layouts/15/images/staticrefresh.gif" id="ManualRefresh" border="0" onclick="javascript: {ddwrt:GenFireServerEvent('__cancel')}" alt="Click here to refresh the dataview."/>
						</td>
					</tr>
				</table>
			</xsl:when>
								<xsl:otherwise>
									<xsl:call-template name="dvt_1"/>
			</xsl:otherwise>
							</xsl:choose>
	</xsl:template>
						<xsl:template name="dvt_1">
							<xsl:variable name="dvt_StyleName">Table</xsl:variable>
							<xsl:variable name="Rows" select="/dsQueryResponse/Rows/Row"/>
							<xsl:variable name="dvt_RowCount" select="count($Rows)"/>
							<xsl:variable name="RowLimit" select="10" />
							<xsl:variable name="FirstRow" select="$dvt_firstrow" />
							<xsl:variable name="LastRow" select="$FirstRow + $dvt_RowCount - 1" />
							<xsl:variable name="IsEmpty" select="$dvt_RowCount = 0" />
							<xsl:variable name="dvt_IsEmpty" select="$dvt_RowCount = 0"/>
							
							<xsl:choose>
								<xsl:when test="$dvt_IsEmpty">
									<xsl:call-template name="dvt_1.empty"/>
			</xsl:when>
								<xsl:otherwise>
				<table border="0" width="100%" cellpadding="2" cellspacing="0">
					<tr valign="top">
						<xsl:if test="$dvt_1_automode = '1'" ddwrt:cf_ignore="1">
							<th class="ms-vh" width="1%" nowrap="nowrap"></th>
						</xsl:if>
						<th class="ms-vh" nowrap="nowrap">Priority</th>
						<th class="ms-vh" nowrap="nowrap">Task Status</th>
						<th class="ms-vh" nowrap="nowrap">Due Date</th>
					</tr>
					<xsl:call-template name="dvt_1.body">
						<xsl:with-param name="Rows" select="$Rows"/>
						<xsl:with-param name="FirstRow" select="1" />
						<xsl:with-param name="LastRow" select="$LastRow - $FirstRow + 1" />
					</xsl:call-template>
				</table>
			</xsl:otherwise>
							</xsl:choose>
							<xsl:call-template name="dvt_1.commandfooter">
								<xsl:with-param name="FirstRow" select="$FirstRow" />
								<xsl:with-param name="LastRow" select="$LastRow" />
								<xsl:with-param name="RowLimit" select="$RowLimit" />
								<xsl:with-param name="dvt_RowCount" select="$dvt_RowCount" />
								<xsl:with-param name="RealLastRow" select="number(ddwrt:NameChanged('',-100))" />
							</xsl:call-template>
						</xsl:template>
						<xsl:template name="dvt_1.body">
							<xsl:param name="Rows"/>
							<xsl:param name="FirstRow" />
							<xsl:param name="LastRow" />
							<xsl:for-each select="$Rows">
								<xsl:variable name="dvt_KeepItemsTogether" select="false()" />
								<xsl:variable name="dvt_HideGroupDetail" select="false()" />
								<xsl:if test="(position() &gt;= $FirstRow and position() &lt;= $LastRow) or $dvt_KeepItemsTogether">
									<xsl:if test="not($dvt_HideGroupDetail)" ddwrt:cf_ignore="1">
										<xsl:call-template name="dvt_1.rowview" />
									</xsl:if>
								</xsl:if>
							</xsl:for-each>
	</xsl:template>
						<xsl:template name="dvt_1.rowview">
		<tr>
			<xsl:if test="position() mod 2 = 1">
				<xsl:attribute name="class">ms-alternating</xsl:attribute>
			</xsl:if>
			<xsl:if test="$dvt_1_automode = '1'" ddwrt:cf_ignore="1">
				<td class="ms-vb" width="1%" nowrap="nowrap">
					<span ddwrt:amkeyfield="ID" ddwrt:amkeyvalue="ddwrt:EscapeDelims(string(@ID))" ddwrt:ammode="view"></span>
				</td>
			</xsl:if>
			<td class="ms-vb">
				<xsl:value-of select="@Priority"/>
			</td>
			<td class="ms-vb">
				<xsl:value-of select="@Status"/>
			</td>
			<td class="ms-vb">
				<xsl:value-of select="@DueDate"/>
			</td>
		</tr>
	</xsl:template>
						<xsl:template name="dvt_1.empty">
							<xsl:variable name="dvt_ViewEmptyText">There are no items to show in this view.</xsl:variable>
		<table border="0" width="100%">
			<tr>
				<td class="ms-vb">
					<xsl:value-of select="$dvt_ViewEmptyText"/>
				</td>
			</tr>
		</table>
	</xsl:template>
						<xsl:template name="dvt_1.commandfooter">
							<xsl:param name="FirstRow" />
							<xsl:param name="LastRow" />
							<xsl:param name="RowLimit" />
							<xsl:param name="dvt_RowCount" />
							<xsl:param name="RealLastRow" />
							<table cellspacing="0" cellpadding="4" border="0" width="100%">
			<tr>
				<xsl:if test="$FirstRow &gt; 1 or $dvt_nextpagedata">
					<xsl:call-template name="dvt_1.navigation">
						<xsl:with-param name="FirstRow" select="$FirstRow" />
						<xsl:with-param name="LastRow" select="$LastRow" />
						<xsl:with-param name="RowLimit" select="$RowLimit" />
						<xsl:with-param name="dvt_RowCount" select="$dvt_RowCount" />
						<xsl:with-param name="RealLastRow" select="$RealLastRow" />
					</xsl:call-template>
				</xsl:if>
								</tr>
		</table>
						</xsl:template>
						<xsl:template name="dvt_1.navigation">
							<xsl:param name="FirstRow" />
							<xsl:param name="LastRow" />
							<xsl:param name="RowLimit" />
							<xsl:param name="dvt_RowCount" />
							<xsl:param name="RealLastRow" />
							<xsl:variable name="PrevRow">
								<xsl:choose>
									<xsl:when test="$FirstRow - $RowLimit &lt; 1">1</xsl:when>
									<xsl:otherwise>
					<xsl:value-of select="$FirstRow - $RowLimit" />
				</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="LastRowValue">
								<xsl:choose>
									<xsl:when test="$LastRow &gt; $RealLastRow">
					<xsl:value-of select="$LastRow"></xsl:value-of>
				</xsl:when>
									<xsl:otherwise>
					<xsl:value-of select="$RealLastRow"></xsl:value-of>
				</xsl:otherwise>
								</xsl:choose>
							</xsl:variable>
							<xsl:variable name="NextRow">
			<xsl:value-of select="$LastRowValue + 1"></xsl:value-of>
		</xsl:variable>
							<td nowrap="nowrap" class="ms-paging" align="right">
								<xsl:if test="$dvt_firstrow &gt; 1" ddwrt:cf_ignore="1">
				<a>
									<xsl:attribute name="href">javascript: <xsl:value-of select="ddwrt:GenFireServerEvent('dvt_firstrow={1};dvt_startposition={}')" />;</xsl:attribute>
									Start</a>
									<xsl:text disable-output-escaping="yes" ddwrt:nbsp-preserve="yes">&amp;nbsp;</xsl:text>
									<a>
									<xsl:attribute name="href">javascript: history.back();</xsl:attribute>
									<img src="/_layouts/15/images/prev.gif" border="0" alt="Previous" />
									</a>
									<xsl:text disable-output-escaping="yes" ddwrt:nbsp-preserve="yes">&amp;nbsp;</xsl:text>
								</xsl:if>
								<xsl:value-of select="$FirstRow" />
								 - <xsl:value-of select="$LastRowValue" />
								<xsl:text disable-output-escaping="yes" ddwrt:nbsp-preserve="yes">&amp;nbsp;</xsl:text>
								<xsl:if test="$LastRowValue &lt; $dvt_RowCount or string-length($dvt_nextpagedata)!=0" ddwrt:cf_ignore="1">
				<a>
									<xsl:attribute name="href">javascript: <xsl:value-of select="ddwrt:GenFireServerEvent(concat('dvt_firstrow={',$NextRow,'};dvt_startposition={',$dvt_nextpagedata,'}'))" />;</xsl:attribute>
									<img src="/_layouts/15/images/next.gif" border="0" alt="Next" />
									</a>
			</xsl:if>
							</td>
						</xsl:template>
					</xsl:stylesheet></XSL>
<parameterbindings>
						<ParameterBinding Name="ListID" Location="None" DefaultValue="42A67DEE-9661-4FA3-AB8C-F0C4F2D62B1B"/>
						<ParameterBinding Name="dvt_apos" Location="Postback;Connection"/>
						<ParameterBinding Name="ManualRefresh" Location="WPProperty[ManualRefresh]"/>
						<ParameterBinding Name="UserID" Location="CAMLVariable" DefaultValue="CurrentUserName"/>
						<ParameterBinding Name="Today" Location="CAMLVariable" DefaultValue="CurrentDate"/>
						<ParameterBinding Name="dvt_startposition" Location="Postback" DefaultValue=""/>
						<ParameterBinding Name="dvt_firstrow" Location="Postback;Connection"/>
						<ParameterBinding Name="dvt_nextpagedata" Location="Postback;Connection"/>
					</parameterbindings></WebPartPages:DataFormWebPart>
					
					</ZoneTemplate></WebPartPages:WebPartZone> </td>
				</tr>
				<tr>
					<td id="_invisibleIfEmpty" name="_invisibleIfEmpty" valign="top" height="100%"> 
					<WebPartPages:WebPartZone runat="server" Title="loc:LeftColumn" ID="LeftColumn" FrameType="TitleBarOnly"><ZoneTemplate></ZoneTemplate></WebPartPages:WebPartZone> </td>
					<td id="_invisibleIfEmpty" name="_invisibleIfEmpty" valign="top" height="100%"> 
					<WebPartPages:WebPartZone runat="server" Title="loc:MiddleColumn" ID="MiddleColumn" FrameType="TitleBarOnly"><ZoneTemplate></ZoneTemplate></WebPartPages:WebPartZone> </td>
					<td id="_invisibleIfEmpty" name="_invisibleIfEmpty" valign="top" height="100%"> 
					<WebPartPages:WebPartZone runat="server" Title="loc:RightColumn" ID="RightColumn" FrameType="TitleBarOnly"><ZoneTemplate></ZoneTemplate></WebPartPages:WebPartZone> </td>
				</tr>
				<tr>
					<td id="_invisibleIfEmpty" name="_invisibleIfEmpty" colspan="3" valign="top" width="100%"> 
					<WebPartPages:WebPartZone runat="server" Title="loc:Footer" ID="Footer" FrameType="TitleBarOnly"><ZoneTemplate></ZoneTemplate></WebPartPages:WebPartZone> </td>
				</tr>
				<SharePoint:ScriptBlock runat="server">
				if(typeof(MSOLayout_MakeInvisibleIfEmpty) == &quot;function&quot;) 
				{MSOLayout_MakeInvisibleIfEmpty();}</SharePoint:ScriptBlock>
		</table>
</asp:Content>

**Comment by kenhughlee** [comment]
I emailed you.

**Comment by sg-chrishasz** [comment]
Hello @kenhughlee - Thanks for sending over all of the files. If I understand correctly, you are editing/adding web part or markup directly to a the content region of a page in the pages (or sitepages) library.

Unfortunately this is one of those SharePoint outliers - all of the content in pages is actually stored in SharePoint's ContentDB and would require additional webservice calls which are not currently supported by SPGo.

Since you are working with a DataForm Webpart, my recommendation would be to create this as a custom webpart in the webparts gallery. You can then edit/modify this web part using SPGo by synchronizing the _catalogs/wp folder of your SharePoint site. Also, this allows you to reuse this webpart easily across sites or pages. I've used this same method successfully in the past to manage custom webparts on pages.

Thanks!

**Comment by kenhughlee** [comment]
Okay. Thanks for looking into that.
