### ISSUE TITLE
SPGo doesn't take masterpages and pagelayouts with same name Sitecollection

### ISSUE THREAD

**Issue by richyreys** [readysitego/spgo#80]
For some reason, SPGo doesn't recognize pages layouts, materpage and folders with the same name that the sitecollection
![6c0a1842](https://user-images.githubusercontent.com/1608151/53644975-a499ca00-3c16-11e9-82b9-56eed8eb8819.PNG)

But when you changes or rename the file with another name, it now passes to show.  

![spgo](https://user-images.githubusercontent.com/1608151/53645289-50dbb080-3c17-11e9-8ca4-37916df00c1c.PNG)

**Comment by richyreys** [comment]
Now i look up that the problem is similar with #69 issue opened by @tockata Workspace wrong population - files renamed and moved out of folder #69.
Now it's only waiting the next version.

**Comment by sg-chrishasz** [comment]
@richyreys - I've just posted SPGo 1.3.5 to the VSCode Marketplace which will resolve this issue. Please reopen this issue if you are still experiencing issues.
